### PR TITLE
Updating CustomSounds, SRModCore, SRPlaylistManager, SRVoting, Trashbin mods, and adding SRFastScrollButtons mod

### PR DESCRIPTION
**Pull request by Chipdancer**
Updating CustomSounds to 1.2.0
Updating SRModCore to 1.1.0
Updating SRPlaylistManager to 1.2.0
Updating SRVoting to 1.3.0
Updating Trashbin to 1.3.0

Added SRFastScrollButtons 1.2.0

### CODE REVIEW

**Comment by Chipdancer** [comment]
Also, hai @bookdude13 and @tommaier123! 🤣

**Comment by bookdude13** [comment]
Hi @Chipdancer! Thanks for the PR. Looks like SRModCore is missing the LocalInfo.json file, but the others look good

**Comment by Chipdancer** [comment]
> Hi @Chipdancer! Thanks for the PR. Looks like SRModCore is missing the LocalInfo.json file, but the others look good

I just pulled them from their public repositories and created the `.synthmod` archives for them per the spec (AIUI).

**Comment by bookdude13** [comment]
Ah shoot then my SRModCore upload was wrong, I'll fix that

**Comment by Chipdancer** [comment]
Hopefully this resolves the outstanding issue, @bookdude13.  Thanks for the fix.

**Pull request merged**
